---

examples:

  -
    title: "Line Charts"
    dir: "linecharts"
    examples:
      -
        title: "Simple timeseries line chart"
        file: "simple_lines"
        url: "/linecharts/simple_lines"
      -
        title: "Lines with points"
        file: "lines_with_points"
        url: "/linecharts/lines_with_points"
      -
        title: "Explicit range/domain"
        file: "explicit_domain"
        url: "/linecharts/explicit_domain"
      -
        title: "Lines with data labels"
        file: "lines_with_labels"
        url: "/linecharts/lines_with_labels"
      -
        title: "Multiple Y Axes"
        file: "multiple_y_axes"
        url: "/linecharts/multiple_y_axes"
      -
        title: "Logarithmic domain"
        file: "logarithmic_domain"
        url: "/linecharts/logarithmic_domain"
#      -
#        title: "Line and Point styles"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
      -
        title: "Data with irregular intervals"
        file: "irregular_intervals"
        url: "/linecharts/irregular_data"
#      -
#        title: "Lines with missing data"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
      -
        title: "Inverted Axis"
        file: "inverted_axis"
        url: "/linecharts/inverted_axis"

  -
    title: "Area Charts"
    dir: "areacharts"
    examples:
      -
        title: "Simple area chart"
        file: "simple_area"
        url: "/areacharts/simple_area"
      -
        title: "Area with borders/points"
        file: "area_with_points"
        url: "/areacharts/area_with_points"
#      -
#        title: "Stacked areas"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
      -
        title: "Area ranges"
        file: "area_ranges"
        url: "/areacharts/area_ranges"

  -
    title: "Bar Charts"
    dir: "barcharts"
    examples:
      -
        title: "Vertical bar chart, multiple series"
        file: "vertical_bars"
        url: "/barcharts/vertical_bars"
      -
        title: "Horizontal bar chart with labels"
        file: "horizontal_bars"
        url: "/barcharts/horizontal_bars"
      -
        title: "Stacked Bar Chart"
        file: "stacked_bars"
        url: "/barcharts/stacked_bars"
      -
        title: "Vertical range bars"
        file: "vertical_ranges"
        url: "/barcharts/vertical_ranges"
      -
        title: "Horizontal range bars"
        file: "horizontal_ranges"
        url: "/barcharts/horizontal_ranges"
#      -
#        title: "Histogram"
#        file: "horizontal_bars"
      -
        title: "Bars with negative values"
        file: "negative_values"
        url: "/barcharts/negative_values"

  -
    title: "Bubble &amp; Scatter Charts"
    dir: "barcharts"
    examples:
      -
        title: "Simple bubble chart"
        file: "simple_bubble_chart"
        url: "/pointcharts/simple_bubbles"
      -
        title: "Simple scatter chart"
        file: "simple_scatter_chart"
        url: "/pointcharts/simple_scatter"
      -
        title: "Point chart with data labels"
        file: "pointchart_with_labels"
        url: "/pointcharts/pointchart_with_labels"
#      -
#        title: "Points with middle axis"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#
  -
    title: "Combined Charts"
    dir: "combined"
    examples:
      -
        title: "Bars and Lines"
        file: "bars_and_lines"
        url: "/combined/barsandlines"
#      -
#        title: "Lines with error bars"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
      -
        title: "Areas with lines"
        file: "arearange_and_line"
        url: "/combined/arearange_and_line"

#  -
#    title: "Axis &amp Legend"
#    dir: "styles"
#    examples:
#      -
#        title: "Rotated axis labels"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Axis styles"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Horizontal grid"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Horizontal &amp; Vertical grid"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Legend outside, Axes inside"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"

#  -
#    title: "Custom styles"
#    dir: "styles"
#    examples:
#      -
#        title: "Default Style"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#      -
#        title: "Dark Style"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"
#
#  -
#    title: "Dashboards"
#    dir: "dashboards"
#    examples:
#      -
#        title: "Web application"
#        file: "horizontal_bars"
#        url: "/barcharts/horizontal_bars"

#  * horizontal with labels outside
#  * horizontal with labels inside
#  * multiple y axis

documentation:
  -
    title: "Using FnordMetric"
    pages:
      -
        title: "Getting Started"
        url: "/"
        file: "getting_started"
      -
        title: "Installation"
        url: "/query_language/reference"
      -
        title: "Using fnordmetric-server"
        url: "/query_language/reference"
      -
        title: "Using fnordmetric-cli"
        url: "/query_language/reference"


  -
    title: "Query Language (ChartSQL)"
    pages:
      -
        title: "Introduction"
        url: "/query_language/overview"
      -
        title: "Drawing Charts"
        url: "/query_language/reference"
      -
        title: "Time-window Aggregations"
        url: "/query_language/timewindow_aggregations"
        file: "timewindow_aggregations"
      -
        title: "External Data Sources"
        url: "/query_language/reference"
      -
        title: "Built-in Functions"
        url: "/query_language/reference"
      -
        title: "Syntax Reference"
        url: "/query_language/reference"

  -
    title: "Collecting Data"
    pages:
      -
        title: "Metrics &amp; Labels"
        url: "/query_language/reference"
      -
        title: "Sending data via HTTP"
        url: "/query_language/reference"
      -
        title: "Sending data via statsd"
        url: "/query_language/reference"
      -
        title: "Retention Policies"
        url: "/query_language/reference"
      -
        title: "Included agents"
        url: "/query_language/reference"

  -
    title: "Building Dashboards"
    pages:
      -
        title: "Dashboards"
        url: "/query_language/reference"
      -
        title: "HTML5 API Reference"
        url: "/query_language/reference"

  -
    title: "Customizing Charts"
    pages:
      -
        title: "Axis styles"
        url: "/query_language/reference"
      -
        title: "Legend styles"
        url: "/query_language/reference"
      -
        title: "Point and Line styles"
        url: "/query_language/reference"
      -
        title: "Line Charts"
        url: "/query_language/reference"
      -
        title: "Point Charts"
        url: "/query_language/reference"
      -
        title: "Area Charts"
        url: "/query_language/reference"
      -
        title: "Bar Charts"
        url: "/query_language/reference"
      -
        title: "Combining Charts"
        url: "/query_language/reference"
      -
        title: "Timeseries Data"
        url: "/query_language/reference"
      -
        title: "Multiple Domains"
        url: "/query_language/reference"
      -
        title: "Interactive Charts"
        url: "/query_language/reference"
      -
        title: "Styles / Themes"
        url: "/query_language/reference"

  -
    title: "FnordMetric APIs &amp Clients"
    pages:
      -
        title: "FnordMetric HTTP API"
        url: "/query_language/reference"
      -
        title: "FnordMetric statsd API"
        url: "/query_language/reference"
      -
        title: "FnordMetric for JavaScript"
        url: "/query_language/reference"
      -
        title: "FnordMetric for Ruby (on Rails)"
        url: "/query_language/reference"


  -
    title: "Hacking"
    pages:
      -
        title: "Contributing"
        url: "/enterprise_api_reference"
      -
        title: "Old Documentation"
        url: "/enterprise_usage"

