---


sitemap:

  fnordmetric_ui:
    -
      title: "Getting started"
      url: "/ui_index"

  fnordmetric_classic:
    -
      title: "Getting started"
      url: "/classic_index"

  fnordmetric_enterprise:
    -
      title: "Getting started"
      url: "/ui_index"
