---


sitemap:

  fnordmetric_ui:
    -
      title: "Getting Started"
      url: "/ui_index"

  fnordmetric_classic:
    -
      title: "Getting Started"
      url: "/classic_index"
    -
      title: "Gauges"
      url: "/classic_gauges"

  fnordmetric_enterprise:
    -
      title: "Getting Started"
      url: "/ui_index"
